'use client';

import React, { useMemo } from 'react';
import jsPDF from 'jspdf';
import { ProToolBase } from '@/components/ProToolBase';
import { TOOLS } from '@/lib/config';
import { Calendar, Cake, Clock, Sparkles } from 'lucide-react';

export function AgeCalculatorTool() {
  const tool = TOOLS.find((t) => t.slug === 'age-calculator') || {
    slug: 'age-calculator',
    name: 'Age Calculator',
    desc: 'Calculate exact age from date of birth in years, months, days.',
    tag: 'Calc',
    colorIndex: 7,
  };

  const calculateAgeDetails = (birthDateStr: string) => {
    if (!birthDateStr) return null;
    const birth = new Date(birthDateStr);
    const now = new Date();
    if (isNaN(birth.getTime()) || birth > now) return null;

    let years = now.getFullYear() - birth.getFullYear();
    let months = now.getMonth() - birth.getMonth();
    let days = now.getDate() - birth.getDate();

    if (days < 0) {
      months -= 1;
      const prevMonthLastDay = new Date(now.getFullYear(), now.getMonth(), 0).getDate();
      days += prevMonthLastDay;
    }
    if (months < 0) {
      years -= 1;
      months += 12;
    }

    const diffMs = now.getTime() - birth.getTime();
    const totalDays = Math.floor(diffMs / (1000 * 60 * 60 * 24));
    const totalHours = Math.floor(diffMs / (1000 * 60 * 60));
    const totalWeeks = Math.floor(totalDays / 7);

    // Next birthday calculation
    let nextBday = new Date(now.getFullYear(), birth.getMonth(), birth.getDate());
    if (nextBday < now) {
      nextBday = new Date(now.getFullYear() + 1, birth.getMonth(), birth.getDate());
    }
    const daysUntilNext = Math.ceil((nextBday.getTime() - now.getTime()) / (1000 * 60 * 60 * 24));

    return {
      years,
      months,
      days,
      totalDays,
      totalHours,
      totalWeeks,
      daysUntilNext,
      dayOfWeek: birth.toLocaleDateString('en-US', { weekday: 'long' }),
    };
  };

  const generateAgeCertificatePdf = (form: Record<string, any>) => {
    const details = calculateAgeDetails(form.birthDate);
    if (!details) {
      alert('Please select a valid date of birth.');
      return;
    }

    const doc = new jsPDF({
      orientation: 'landscape',
      unit: 'pt',
      format: 'a4',
    });

    const userName = form.userName || 'Special Person';

    // Outer decorative borders
    doc.setDrawColor(37, 99, 235);
    doc.setLineWidth(3);
    doc.rect(20, 20, 802, 555);

    doc.setDrawColor(203, 213, 225);
    doc.setLineWidth(1);
    doc.rect(26, 26, 790, 543);

    // Header banner
    doc.setFillColor(37, 99, 235);
    doc.rect(30, 30, 782, 70, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(26);
    doc.text('OFFICIAL AGE & CHRONOLOGICAL MILESTONE RECORD', 421, 74, { align: 'center' });

    // Certificate text
    doc.setTextColor(30, 41, 59);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'normal');
    doc.text('This certifies that on this day, the chronological record for', 421, 140, { align: 'center' });

    doc.setTextColor(37, 99, 235);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(30);
    doc.text(userName.toUpperCase(), 421, 185, { align: 'center' });

    doc.setTextColor(71, 85, 105);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'normal');
    doc.text(`Born on ${new Date(form.birthDate).toLocaleDateString('en-US', { dateStyle: 'full' })} (a ${details.dayOfWeek})`, 421, 215, { align: 'center' });

    // Highlight Box: Exact Age
    doc.setFillColor(241, 245, 249);
    doc.roundedRect(120, 240, 602, 70, 8, 8, 'F');

    doc.setTextColor(15, 23, 42);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(22);
    doc.text(
      `${details.years} Years, ${details.months} Months, and ${details.days} Days`,
      421,
      282,
      { align: 'center' }
    );

    // Milestone Grid
    const colY = 340;
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(51, 65, 85);

    const stats = [
      `Total Days Lived: ${details.totalDays.toLocaleString()} days`,
      `Total Weeks: ${details.totalWeeks.toLocaleString()} weeks`,
      `Total Hours: ~${details.totalHours.toLocaleString()} hours`,
      `Next Birthday Countdown: ${details.daysUntilNext} days remaining`,
    ];

    stats.forEach((st, idx) => {
      const colX = idx % 2 === 0 ? 160 : 460;
      const rowY = colY + Math.floor(idx / 2) * 32;
      doc.setFillColor(248, 250, 252);
      doc.roundedRect(colX, rowY, 260, 24, 4, 4, 'F');
      doc.text(st, colX + 15, rowY + 16);
    });

    // Verification Footer
    doc.setFontSize(9);
    doc.setTextColor(148, 163, 184);
    doc.text(`Generated by AllToolsPK (alltoolspk.com) • 100% Client-Side Chronological Engine`, 421, 520, { align: 'center' });
    doc.text(`Timestamp: ${new Date().toUTCString()}`, 421, 535, { align: 'center' });

    const safeName = userName.trim().replace(/\s+/g, '_') || 'Person';
    doc.save(`${safeName}_Age_Milestone_Record.pdf`);
  };

  return (
    <ProToolBase
      tool={tool}
      required={['userName', 'birthDate']}
      initialState={{
        userName: '',
        birthDate: '',
      }}
      render={(form, setForm) => {
        const details = form.birthDate ? calculateAgeDetails(form.birthDate) : null;

        return (
          <div className="space-y-6">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 uppercase tracking-wider mb-1.5">
                  Full Name or Nickname *
                </label>
                <input
                  type="text"
                  placeholder="e.g. Jordan Smith"
                  value={form.userName || ''}
                  onChange={(e) => setForm({ ...form, userName: e.target.value })}
                  className="w-full px-4 py-3 rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-base sm:text-sm focus:ring-2 focus:ring-blue-600 outline-none"
                />
              </div>

              <div>
                <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 uppercase tracking-wider mb-1.5">
                  Date of Birth *
                </label>
                <input
                  type="date"
                  value={form.birthDate || ''}
                  onChange={(e) => setForm({ ...form, birthDate: e.target.value })}
                  className="w-full px-4 py-3 rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-base sm:text-sm focus:ring-2 focus:ring-blue-600 outline-none cursor-pointer"
                />
              </div>
            </div>

            {/* Live Age Display */}
            {details && (
              <div className="p-6 rounded-2xl bg-gradient-to-br from-blue-50 to-indigo-50/50 dark:from-slate-800 dark:to-slate-800/60 border border-blue-100 dark:border-slate-700 space-y-4">
                <div className="text-center space-y-1">
                  <span className="text-xs font-bold uppercase tracking-wider text-blue-600 dark:text-blue-400">
                    Exact Age Today
                  </span>
                  <p className="text-2xl sm:text-3xl font-black text-slate-900 dark:text-white">
                    {details.years} <span className="text-sm font-normal text-slate-500">years</span>{' '}
                    {details.months} <span className="text-sm font-normal text-slate-500">months</span>{' '}
                    {details.days} <span className="text-sm font-normal text-slate-500">days</span>
                  </p>
                  <p className="text-xs text-slate-500">
                    Born on a {details.dayOfWeek}
                  </p>
                </div>

                <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-center pt-2">
                  <div className="p-3 bg-white dark:bg-slate-900 rounded-xl shadow-xs">
                    <span className="text-[10px] text-slate-400 uppercase font-bold block">Total Days</span>
                    <span className="text-base font-extrabold text-slate-800 dark:text-slate-200">
                      {details.totalDays.toLocaleString()}
                    </span>
                  </div>
                  <div className="p-3 bg-white dark:bg-slate-900 rounded-xl shadow-xs">
                    <span className="text-[10px] text-slate-400 uppercase font-bold block">Total Weeks</span>
                    <span className="text-base font-extrabold text-slate-800 dark:text-slate-200">
                      {details.totalWeeks.toLocaleString()}
                    </span>
                  </div>
                  <div className="p-3 bg-white dark:bg-slate-900 rounded-xl shadow-xs">
                    <span className="text-[10px] text-slate-400 uppercase font-bold block">Total Hours</span>
                    <span className="text-base font-extrabold text-slate-800 dark:text-slate-200">
                      ~{details.totalHours.toLocaleString()}
                    </span>
                  </div>
                  <div className="p-3 bg-white dark:bg-slate-900 rounded-xl shadow-xs">
                    <span className="text-[10px] text-slate-400 uppercase font-bold block">Next Birthday</span>
                    <span className="text-base font-extrabold text-emerald-600">
                      {details.daysUntilNext} days
                    </span>
                  </div>
                </div>
              </div>
            )}
          </div>
        );
      }}
      generateFile={generateAgeCertificatePdf}
    />
  );
}

export default AgeCalculatorTool;
