'use client';

import React, { useMemo } from 'react';
import jsPDF from 'jspdf';
import { ProToolBase } from '@/components/ProToolBase';
import { TOOLS } from '@/lib/config';
import { vatCountries, VatCountry } from '@/lib/vatCountries';

export function AmazonEuVatTool() {
  const tool = TOOLS.find((t) => t.slug === 'amazon-eu-vat') || {
    slug: 'amazon-eu-vat',
    name: 'Amazon EU VAT Calculator',
    desc: 'Calculate destination EU VAT rates, net turnover amounts, and generate bulk PDF invoices.',
    tag: 'EU OSS Ready',
    colorIndex: 0,
  };

  const getCountryRate = (code: string, customRateStr?: string) => {
    const found = vatCountries.find((c) => c.code === code);
    if (!found) return { name: 'Germany', rate: 19, code: 'DE' };
    if (found.code === 'OTHER' || found.custom) {
      const parsed = parseFloat(customRateStr || '0');
      return {
        name: 'Custom Jurisdiction',
        rate: isNaN(parsed) ? 0 : parsed,
        code: 'OTHER',
      };
    }
    return found;
  };

  const generateVatInvoicePdf = (form: Record<string, any>) => {
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'pt',
      format: 'a4',
    });

    const buyerName = form.buyerName || 'Valued Customer';
    const countryCode = form.country || 'PK';
    const rateInfo = getCountryRate(countryCode, form.customRate);
    const gross = parseFloat(form.grossAmount) || 0;
    const net = gross / (1 + rateInfo.rate / 100);
    const vatAmount = gross - net;
    const invNumber = form.invoiceNumber || `INV-${Date.now().toString().slice(-6)}`;
    const orderId = form.orderId || `AMZ-${Date.now().toString().slice(-8)}`;

    // PDF Design
    doc.setFillColor(37, 99, 235);
    doc.rect(0, 0, 595, 80, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(22);
    doc.text('VAT COMMERCIAL INVOICE', 40, 48);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('Generated by AllToolsPK • Global VAT & OSS Compliant', 40, 66);

    // Metadata
    doc.setTextColor(51, 65, 85);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text('Invoice Details:', 40, 120);

    doc.setFont('helvetica', 'normal');
    doc.text(`Invoice No: ${invNumber}`, 40, 140);
    doc.text(`Order Reference: ${orderId}`, 40, 158);
    doc.text(`Billing Date: ${new Date().toLocaleDateString()}`, 40, 176);

    doc.setFont('helvetica', 'bold');
    doc.text('Customer & Tax Jurisdiction:', 320, 120);
    doc.setFont('helvetica', 'normal');
    doc.text(`Customer: ${buyerName}`, 320, 140);
    doc.text(`Destination: ${rateInfo.name} (${rateInfo.code})`, 320, 158);
    doc.text(`Standard Applicable Rate: ${rateInfo.rate}%`, 320, 176);

    // Table Header
    doc.setFillColor(241, 245, 249);
    doc.rect(40, 210, 515, 28, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(30, 41, 59);
    doc.text('Item Description', 50, 228);
    doc.text('Net Turnover', 260, 228);
    doc.text(`Tax (${rateInfo.rate}%)`, 380, 228);
    doc.text('Gross Total', 480, 228);

    // Table Content Row
    doc.setFont('helvetica', 'normal');
    doc.text('Amazon Marketplace Fulfilled Merchandise', 50, 260);
    doc.text(`€ ${net.toFixed(2)}`, 260, 260);
    doc.text(`€ ${vatAmount.toFixed(2)}`, 380, 260);
    doc.text(`€ ${gross.toFixed(2)}`, 480, 260);

    // Summary Box
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(300, 310, 255, 110, 6, 6, 'F');

    doc.setFont('helvetica', 'normal');
    doc.text('Subtotal (Net Excl. VAT):', 320, 335);
    doc.text(`€ ${net.toFixed(2)}`, 480, 335);

    doc.text(`Total VAT (${rateInfo.rate}%):`, 320, 360);
    doc.text(`€ ${vatAmount.toFixed(2)}`, 480, 360);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42);
    doc.text('Invoice Total (Gross):', 320, 395);
    doc.text(`€ ${gross.toFixed(2)}`, 480, 395);

    // Legal / AdSense Footer
    doc.setFontSize(9);
    doc.setTextColor(148, 163, 184);
    doc.setFont('helvetica', 'normal');
    doc.text(
      'Tax Computation Notice: Certified 100% Client-Side Invoicing via alltoolspk.com.',
      40,
      480
    );
    doc.text(
      'Compliant with European Commission VAT OSS rules and international cross-border trade standards.',
      40,
      496
    );

    const safeName = buyerName.trim().replace(/\s+/g, '_') || 'Customer';
    doc.save(`${safeName}_VAT_Invoice.pdf`);
  };

  return (
    <ProToolBase
      tool={tool}
      required={['buyerName', 'grossAmount']}
      initialState={{
        buyerName: '',
        grossAmount: '',
        country: 'PK',
        customRate: '18',
        invoiceNumber: 'INV-2026-001',
        orderId: '',
      }}
      render={(form, setForm) => {
        const countryCode = form.country || 'PK';
        const isCustom = countryCode === 'OTHER';
        const rateInfo = getCountryRate(countryCode, form.customRate);
        const gross = parseFloat(form.grossAmount) || 0;
        const net = gross > 0 ? gross / (1 + rateInfo.rate / 100) : 0;
        const vat = gross > 0 ? gross - net : 0;

        return (
          <div className="space-y-6">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 uppercase tracking-wider mb-1.5">
                  Buyer / Customer Name *
                </label>
                <input
                  type="text"
                  placeholder="e.g. John Doe or Enterprise GmbH"
                  value={form.buyerName || ''}
                  onChange={(e) => setForm({ ...form, buyerName: e.target.value })}
                  className="w-full px-4 py-3 rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-base sm:text-sm focus:ring-2 focus:ring-blue-600 outline-none"
                />
              </div>

              <div>
                <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 uppercase tracking-wider mb-1.5">
                  Gross Order Total (€ EUR) *
                </label>
                <input
                  type="number"
                  step="0.01"
                  placeholder="e.g. 119.00"
                  value={form.grossAmount || ''}
                  onChange={(e) => setForm({ ...form, grossAmount: e.target.value })}
                  className="w-full px-4 py-3 rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-base sm:text-sm focus:ring-2 focus:ring-blue-600 outline-none"
                />
              </div>

              <div>
                <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 uppercase tracking-wider mb-1.5">
                  Destination Country / Tax Jurisdiction
                </label>
                <select
                  value={countryCode}
                  onChange={(e) => {
                    const newCode = e.target.value;
                    const matched = vatCountries.find((c) => c.code === newCode);
                    setForm({
                      ...form,
                      country: newCode,
                      customRate:
                        matched && matched.code !== 'OTHER'
                          ? matched.rate.toString()
                          : form.customRate || '0',
                    });
                  }}
                  className="w-full px-4 py-3 rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-base sm:text-sm focus:ring-2 focus:ring-blue-600 outline-none cursor-pointer"
                >
                  {vatCountries.map((c) => (
                    <option key={c.code} value={c.code}>
                      {c.name} {c.code === 'OTHER' ? '' : `(${c.rate}%)`}
                    </option>
                  ))}
                </select>
              </div>

              {isCustom ? (
                <div>
                  <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 uppercase tracking-wider mb-1.5">
                    Custom VAT / GST Rate (%) *
                  </label>
                  <input
                    type="number"
                    step="0.1"
                    placeholder="e.g. 15.0"
                    value={form.customRate || ''}
                    onChange={(e) => setForm({ ...form, customRate: e.target.value })}
                    className="w-full px-4 py-3 rounded-xl border border-blue-300 dark:border-blue-700 bg-blue-50/50 dark:bg-slate-800 text-base sm:text-sm focus:ring-2 focus:ring-blue-600 outline-none"
                  />
                </div>
              ) : (
                <div>
                  <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 uppercase tracking-wider mb-1.5">
                    Invoice / Order ID (Optional)
                  </label>
                  <input
                    type="text"
                    placeholder="e.g. AMZ-98234"
                    value={form.orderId || ''}
                    onChange={(e) => setForm({ ...form, orderId: e.target.value })}
                    className="w-full px-4 py-3 rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-base sm:text-sm focus:ring-2 focus:ring-blue-600 outline-none"
                  />
                </div>
              )}
            </div>

            {/* Instant Calculation Preview */}
            <div className="p-5 rounded-2xl bg-blue-50/60 dark:bg-blue-950/30 border border-blue-100 dark:border-blue-900/50">
              <div className="flex items-center justify-between mb-3">
                <h4 className="text-xs font-bold uppercase tracking-wider text-blue-900 dark:text-blue-300">
                  Live Calculation Breakdown
                </h4>
                <span className="text-xs font-semibold text-blue-700 dark:text-blue-300 bg-blue-100 dark:bg-blue-900/60 px-2.5 py-0.5 rounded-full">
                  {rateInfo.name} &bull; {rateInfo.rate}% VAT
                </span>
              </div>
              <div className="grid grid-cols-3 gap-3 text-center">
                <div className="p-3 rounded-xl bg-white dark:bg-slate-800 shadow-xs">
                  <span className="text-[11px] text-slate-500 block">Net Turnover</span>
                  <span className="text-base font-black text-slate-900 dark:text-white">
                    € {net.toFixed(2)}
                  </span>
                </div>
                <div className="p-3 rounded-xl bg-white dark:bg-slate-800 shadow-xs">
                  <span className="text-[11px] text-slate-500 block">
                    VAT ({rateInfo.rate}%)
                  </span>
                  <span className="text-base font-black text-blue-600">
                    € {vat.toFixed(2)}
                  </span>
                </div>
                <div className="p-3 rounded-xl bg-white dark:bg-slate-800 shadow-xs">
                  <span className="text-[11px] text-slate-500 block">Gross Total</span>
                  <span className="text-base font-black text-emerald-600">
                    € {gross.toFixed(2)}
                  </span>
                </div>
              </div>
            </div>
          </div>
        );
      }}
      generateFile={generateVatInvoicePdf}
    />
  );
}

export default AmazonEuVatTool;
