'use client';

import React, { useMemo } from 'react';
import jsPDF from 'jspdf';
import { ProToolBase } from '@/components/ProToolBase';
import { TOOLS } from '@/lib/config';

const VAT_RATES: Record<string, { country: string; rate: number }> = {
  DE: { country: 'Germany', rate: 19 },
  FR: { country: 'France', rate: 20 },
  IT: { country: 'Italy', rate: 22 },
  ES: { country: 'Spain', rate: 21 },
  NL: { country: 'Netherlands', rate: 21 },
  BE: { country: 'Belgium', rate: 21 },
  PL: { country: 'Poland', rate: 23 },
  SE: { country: 'Sweden', rate: 25 },
  AT: { country: 'Austria', rate: 20 },
  IE: { country: 'Ireland', rate: 23 },
};

export function AmazonEuVatTool() {
  const tool = TOOLS.find((t) => t.slug === 'amazon-eu-vat') || {
    slug: 'amazon-eu-vat',
    name: 'Amazon EU VAT Calculator',
    desc: 'Calculate destination EU VAT rates, net turnover amounts, and generate bulk PDF invoices.',
    tag: 'EU OSS Ready',
    colorIndex: 0,
  };

  const generateVatInvoicePdf = (form: Record<string, any>) => {
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'pt',
      format: 'a4',
    });

    const buyerName = form.buyerName || 'Valued Customer';
    const countryCode = form.country || 'DE';
    const rateInfo = VAT_RATES[countryCode] || { country: 'Germany', rate: 19 };
    const gross = parseFloat(form.grossAmount) || 0;
    const net = gross / (1 + rateInfo.rate / 100);
    const vatAmount = gross - net;
    const invNumber = form.invoiceNumber || `INV-${Date.now().toString().slice(-6)}`;
    const orderId = form.orderId || `AMZ-${Date.now().toString().slice(-8)}`;

    // PDF Design
    doc.setFillColor(37, 99, 235);
    doc.rect(0, 0, 595, 80, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(22);
    doc.text('EU VAT COMMERCIAL INVOICE', 40, 48);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('Generated by AllToolsPK • EU OSS Compliant', 40, 66);

    // Metadata
    doc.setTextColor(51, 65, 85);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text('Invoice Details:', 40, 120);

    doc.setFont('helvetica', 'normal');
    doc.text(`Invoice Number: ${invNumber}`, 40, 140);
    doc.text(`Order Reference: ${orderId}`, 40, 158);
    doc.text(`Date of Issue: ${new Date().toLocaleDateString('en-GB')}`, 40, 176);

    doc.setFont('helvetica', 'bold');
    doc.text('Customer / Recipient:', 320, 120);
    doc.setFont('helvetica', 'normal');
    doc.text(`Name: ${buyerName}`, 320, 140);
    doc.text(`Destination Country: ${rateInfo.country} (${countryCode})`, 320, 158);
    doc.text(`Applicable VAT Rate: ${rateInfo.rate}%`, 320, 176);

    // Table Header
    doc.setFillColor(241, 245, 249);
    doc.rect(40, 220, 515, 30, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.text('Description', 50, 238);
    doc.text('Net Turnover', 280, 238);
    doc.text(`VAT (${rateInfo.rate}%)`, 380, 238);
    doc.text('Total (EUR)', 480, 238);

    // Table Row
    doc.setFont('helvetica', 'normal');
    doc.text('Amazon FBA Digital / Physical Goods Order', 50, 275);
    doc.text(`€ ${net.toFixed(2)}`, 280, 275);
    doc.text(`€ ${vatAmount.toFixed(2)}`, 380, 275);
    doc.text(`€ ${gross.toFixed(2)}`, 480, 275);

    // Divider
    doc.setDrawColor(203, 213, 225);
    doc.line(40, 310, 555, 310);

    // Totals Box
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.text('Summary Breakdown', 350, 340);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Net Amount: € ${net.toFixed(2)}`, 350, 360);
    doc.text(`Total VAT (${rateInfo.rate}%): € ${vatAmount.toFixed(2)}`, 350, 380);

    doc.setFillColor(239, 246, 255);
    doc.rect(340, 395, 215, 35, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(37, 99, 235);
    doc.text(`Gross Total: € ${gross.toFixed(2)}`, 350, 417);

    // Statutory Footer
    doc.setTextColor(148, 163, 184);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(
      'Tax notice: Cross-border supply within the European Union under OSS (One-Stop Shop) scheme.',
      40,
      500
    );
    doc.text(
      '100% Client-Side calculation and PDF generation via AllToolsPK (alltoolspk.com).',
      40,
      516
    );

    const safeName = buyerName.trim().replace(/\s+/g, '_') || 'Customer';
    doc.save(`${safeName}_EU_VAT_Invoice.pdf`);
  };

  return (
    <ProToolBase
      tool={tool}
      required={['buyerName', 'grossAmount']}
      initialState={{
        buyerName: '',
        grossAmount: '',
        country: 'DE',
        invoiceNumber: 'INV-2026-001',
        orderId: '',
      }}
      render={(form, setForm) => {
        const countryCode = form.country || 'DE';
        const rateInfo = VAT_RATES[countryCode] || { country: 'Germany', rate: 19 };
        const gross = parseFloat(form.grossAmount) || 0;
        const net = gross > 0 ? gross / (1 + rateInfo.rate / 100) : 0;
        const vat = gross > 0 ? gross - net : 0;

        return (
          <div className="space-y-6">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 uppercase tracking-wider mb-1.5">
                  Buyer / Customer Name *
                </label>
                <input
                  type="text"
                  placeholder="e.g. John Doe or Enterprise GmbH"
                  value={form.buyerName || ''}
                  onChange={(e) => setForm({ ...form, buyerName: e.target.value })}
                  className="w-full px-4 py-3 rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-sm focus:ring-2 focus:ring-blue-600 outline-none"
                />
              </div>

              <div>
                <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 uppercase tracking-wider mb-1.5">
                  Gross Order Total (€ EUR) *
                </label>
                <input
                  type="number"
                  step="0.01"
                  placeholder="e.g. 119.00"
                  value={form.grossAmount || ''}
                  onChange={(e) => setForm({ ...form, grossAmount: e.target.value })}
                  className="w-full px-4 py-3 rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-sm focus:ring-2 focus:ring-blue-600 outline-none"
                />
              </div>

              <div>
                <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 uppercase tracking-wider mb-1.5">
                  Destination EU Country
                </label>
                <select
                  value={form.country || 'DE'}
                  onChange={(e) => setForm({ ...form, country: e.target.value })}
                  className="w-full px-4 py-3 rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-sm focus:ring-2 focus:ring-blue-600 outline-none cursor-pointer"
                >
                  {Object.entries(VAT_RATES).map(([code, item]) => (
                    <option key={code} value={code}>
                      {item.country} ({item.rate}% VAT)
                    </option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 uppercase tracking-wider mb-1.5">
                  Invoice / Order ID (Optional)
                </label>
                <input
                  type="text"
                  placeholder="e.g. AMZ-98234"
                  value={form.orderId || ''}
                  onChange={(e) => setForm({ ...form, orderId: e.target.value })}
                  className="w-full px-4 py-3 rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-sm focus:ring-2 focus:ring-blue-600 outline-none"
                />
              </div>
            </div>

            {/* Instant Calculation Preview */}
            <div className="p-5 rounded-2xl bg-blue-50/60 dark:bg-blue-950/30 border border-blue-100 dark:border-blue-900/50">
              <h4 className="text-xs font-bold uppercase tracking-wider text-blue-900 dark:text-blue-300 mb-3">
                Live Calculation Breakdown
              </h4>
              <div className="grid grid-cols-3 gap-3 text-center">
                <div className="p-3 rounded-xl bg-white dark:bg-slate-800 shadow-xs">
                  <span className="text-[11px] text-slate-500 block">Net Turnover</span>
                  <span className="text-base font-black text-slate-900 dark:text-white">
                    € {net.toFixed(2)}
                  </span>
                </div>
                <div className="p-3 rounded-xl bg-white dark:bg-slate-800 shadow-xs">
                  <span className="text-[11px] text-slate-500 block">
                    VAT Amount ({rateInfo.rate}%)
                  </span>
                  <span className="text-base font-black text-blue-600">
                    € {vat.toFixed(2)}
                  </span>
                </div>
                <div className="p-3 rounded-xl bg-white dark:bg-slate-800 shadow-xs">
                  <span className="text-[11px] text-slate-500 block">Gross Total</span>
                  <span className="text-base font-black text-emerald-600">
                    € {gross.toFixed(2)}
                  </span>
                </div>
              </div>
            </div>
          </div>
        );
      }}
      generateFile={generateVatInvoicePdf}
    />
  );
}

export default AmazonEuVatTool;
