'use client';

import React, { useState, useMemo } from 'react';
import jsPDF from 'jspdf';
import {
  ShieldCheck,
  Download,
  Printer,
  FileText,
  AlertTriangle,
  RotateCcw,
  CheckCircle2,
} from 'lucide-react';
import { Button } from '@/components/ui/button';

export const COUNTRIES = [
  { code: 'DE', name: 'Germany', rate: 19, currency: 'EUR', symbol: '€', label: 'Germany (19%)', isEU: true, marketplace: 'de' },
  { code: 'FR', name: 'France', rate: 20, currency: 'EUR', symbol: '€', label: 'France (20%)', isEU: true, marketplace: 'fr' },
  { code: 'IT', name: 'Italy', rate: 22, currency: 'EUR', symbol: '€', label: 'Italy (22%)', isEU: true, marketplace: 'it' },
  { code: 'ES', name: 'Spain', rate: 21, currency: 'EUR', symbol: '€', label: 'Spain (21%)', isEU: true, marketplace: 'es' },
  { code: 'NL', name: 'Netherlands', rate: 21, currency: 'EUR', symbol: '€', label: 'Netherlands (21%)', isEU: true, marketplace: 'nl' },
  { code: 'BE', name: 'Belgium', rate: 21, currency: 'EUR', symbol: '€', label: 'Belgium (21%)', isEU: true, marketplace: 'com.be' },
  { code: 'PL', name: 'Poland', rate: 23, currency: 'PLN', symbol: 'zł', label: 'Poland (23%)', isEU: true, marketplace: 'pl' },
  { code: 'SE', name: 'Sweden', rate: 25, currency: 'SEK', symbol: 'kr', label: 'Sweden (25%)', isEU: true, marketplace: 'se' },
  { code: 'GB', name: 'United Kingdom', rate: 20, currency: 'GBP', symbol: '£', label: 'UK (20% VAT)', isEU: false, marketplace: 'co.uk' },
  { code: 'US', name: 'USA (Export)', rate: 0, currency: 'USD', symbol: '$', label: 'USA (0% Export - Art 146)', isEU: false, marketplace: 'com' },
];

export function AmazonEuVatTool() {
  const [buyer, setBuyer] = useState('');
  const [gross, setGross] = useState('');
  const [countryCode, setCountryCode] = useState('DE');
  const [orderId, setOrderId] = useState('');
  const [seller] = useState({
    company: 'AllToolsPK LTD',
    address: 'Peshawar, Pakistan',
    vatId: 'DE123456789 (OSS)',
    eori: 'DE-EORI-12345',
    ossId: 'EU-OSS-123456',
  });

  const country = useMemo(
    () => COUNTRIES.find((c) => c.code === countryCode) || COUNTRIES[0],
    [countryCode]
  );
  const grossVal = parseFloat(gross) || 0;
  const isExport = country.code === 'US';

  // EU Formula: Gross includes VAT. Net = Gross / (1 + rate)
  const net = isExport ? grossVal : grossVal / (1 + country.rate / 100);
  const vatAmount = grossVal - net;
  const canDownload = buyer.trim().length > 2 && grossVal > 0;

  const generateInvoiceText = () => {
    const legal = isExport
      ? `VAT Exempt - Export Outside EU under Article 146 of EU VAT Directive 2006/112/EC. No VAT charged. Place of supply outside EU.`
      : `VAT Charged under EU OSS Scheme. OSS ID: ${seller.ossId}. Standard rate ${country.rate}% applied per ${country.name} rules (Directive 2006/112/EC).`;

    return `
${isExport ? 'COMMERCIAL INVOICE - EXPORT OUTSIDE EU' : 'VAT COMMERCIAL INVOICE - OSS COMPLIANT'}
Generated by AllToolsPK - 100% Client-Side & EU OSS Ready

SELLER: ${seller.company}
Address: ${seller.address}
VAT ID: ${seller.vatId} | EORI: ${seller.eori} | ${!isExport ? `OSS ID: ${seller.ossId}` : ''}

Invoice No: INV-${new Date().getFullYear()}-${Math.floor(Math.random() * 9000) + 1000}
Order ID: ${orderId || '111-1234567-1234567'} | Date: ${new Date().toLocaleDateString()} | Marketplace: Amazon.${country.marketplace}
BILL TO: ${buyer}
Destination: ${country.name} (${country.code}) | Currency: ${country.currency}

DESCRIPTION: Amazon Marketplace Fulfilled Merchandise
HS CODE: 8517.12.00 | ORIGIN: PK | QTY: 1
Net Turnover: ${country.symbol} ${net.toFixed(2)} ${country.currency}
VAT (${country.rate}%): ${country.symbol} ${vatAmount.toFixed(2)} ${country.currency}
Gross Total: ${country.symbol} ${grossVal.toFixed(2)} ${country.currency}

Tax Notice: ${legal}
Compliant with EU Commission VAT OSS & Amazon Seller Central Invoice Requirements.
`.trim();
  };

  const downloadTxt = () => {
    if (!canDownload) return;
    const blob = new Blob([generateInvoiceText()], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `VAT_Invoice_${country.code}_${buyer.replace(/\s+/g, '_')}_${country.currency}_${grossVal.toFixed(2)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const downloadPdf = () => {
    if (!canDownload) return;
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'pt',
      format: 'a4',
    });

    const invoiceNo = `INV-${new Date().getFullYear()}-${Math.floor(Math.random() * 9000) + 1000}`;
    const orderRef = orderId.trim() || '111-1234567-1234567';

    // Header banner
    doc.setFillColor(15, 23, 42); // slate-900
    doc.rect(0, 0, 595, 75, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.text(
      isExport ? 'COMMERCIAL INVOICE - EXPORT OUTSIDE EU' : 'VAT COMMERCIAL INVOICE - OSS COMPLIANT',
      40,
      42
    );

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text('Generated via AllToolsPK • 100% Client-Side & EU OSS Ready', 40, 58);

    let y = 105;

    // Seller & Invoice columns
    doc.setFontSize(9);
    doc.setTextColor(15, 23, 42);

    // Left: Seller
    doc.setFont('helvetica', 'bold');
    doc.text('SELLER (Exporter):', 40, y);
    doc.setFont('helvetica', 'normal');
    doc.text(seller.company, 40, y + 14);
    doc.text(seller.address, 40, y + 26);
    doc.text(`VAT ID: ${seller.vatId} | EORI: ${seller.eori}`, 40, y + 38);
    if (!isExport) {
      doc.text(`OSS ID: ${seller.ossId}`, 40, y + 50);
    }

    // Right: Invoice Meta
    const rightCol = 360;
    doc.setFont('helvetica', 'bold');
    doc.text('INVOICE REFERENCE:', rightCol, y);
    doc.setFont('helvetica', 'normal');
    doc.text(`Invoice No: ${invoiceNo}`, rightCol, y + 14);
    doc.text(`Order ID: ${orderRef}`, rightCol, y + 26);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, rightCol, y + 38);
    doc.text(`Marketplace: Amazon.${country.marketplace}`, rightCol, y + 50);

    y += 75;

    // Line
    doc.setDrawColor(226, 232, 240);
    doc.line(40, y, 555, y);
    y += 18;

    // Bill To
    doc.setFont('helvetica', 'bold');
    doc.text('BILL TO / CUSTOMER:', 40, y);
    doc.setFont('helvetica', 'normal');
    doc.text(buyer, 40, y + 14);
    doc.text(`Destination: ${country.name} (${country.code}) | Currency: ${country.currency}`, 40, y + 26);

    y += 45;

    // Line Item Table
    doc.setFillColor(241, 245, 249);
    doc.rect(40, y, 515, 22, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.setTextColor(30, 41, 59);
    doc.text('Item Description', 48, y + 14);
    doc.text('HS Code', 260, y + 14);
    doc.text('Qty', 350, y + 14);
    doc.text(`Net (${country.currency})`, 405, y + 14);
    doc.text(`Gross (${country.currency})`, 480, y + 14);

    y += 24;

    doc.setFont('helvetica', 'normal');
    doc.text('Amazon Marketplace Fulfilled Merchandise', 48, y + 14);
    doc.setFontSize(7.5);
    doc.setTextColor(100, 116, 139);
    doc.text('Origin: PK', 48, y + 25);

    doc.setFontSize(8.5);
    doc.setTextColor(30, 41, 59);
    doc.text('8517.12.00', 260, y + 14);
    doc.text('1', 350, y + 14);
    doc.text(`${country.symbol} ${net.toFixed(2)}`, 405, y + 14);
    doc.text(`${country.symbol} ${grossVal.toFixed(2)}`, 480, y + 14);

    y += 40;

    // Totals
    doc.setDrawColor(226, 232, 240);
    doc.line(320, y, 555, y);
    y += 14;

    doc.setFont('helvetica', 'normal');
    doc.text(`Net Turnover:`, 340, y);
    doc.text(`${country.symbol} ${net.toFixed(2)} ${country.currency}`, 480, y);
    y += 14;

    doc.text(`VAT (${country.rate}%):`, 340, y);
    doc.text(`${country.symbol} ${vatAmount.toFixed(2)} ${country.currency}`, 480, y);
    y += 14;

    doc.setDrawColor(15, 23, 42);
    doc.line(320, y, 555, y);
    y += 14;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.text(`Gross Total:`, 340, y);
    doc.text(`${country.symbol} ${grossVal.toFixed(2)} ${country.currency}`, 480, y);

    y += 30;

    // Legal box
    doc.setFillColor(248, 250, 252);
    doc.rect(40, y, 515, 48, 'F');
    doc.setDrawColor(203, 213, 225);
    doc.rect(40, y, 515, 48, 'S');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7.5);
    doc.setTextColor(15, 23, 42);
    doc.text('Tax Notice & Statutory Declaration:', 48, y + 14);

    doc.setFont('helvetica', 'normal');
    doc.setTextColor(71, 85, 105);
    const legalNotice = isExport
      ? `VAT Exempt - Export Outside EU under Article 146 of EU VAT Directive 2006/112/EC. No VAT charged. Place of supply outside EU. Compliant with EU Commission VAT OSS & Amazon Seller Central Invoice Requirements.`
      : `VAT Charged under EU OSS Scheme. OSS ID: ${seller.ossId}. Standard rate ${country.rate}% applied per ${country.name} rules (Directive 2006/112/EC). Compliant with EU Commission VAT OSS & Amazon Seller Central Invoice Requirements.`;

    const noticeLines = doc.splitTextToSize(legalNotice, 495);
    doc.text(noticeLines, 48, y + 26);

    doc.save(`VAT_Invoice_${country.code}_${country.currency}_${grossVal.toFixed(2)}.pdf`);
  };

  const handlePrint = () => {
    if (!canDownload) return;
    window.print();
  };

  const loadSample = () => {
    setBuyer('Enterprise Logistics GmbH');
    setGross('119.00');
    setCountryCode('DE');
    setOrderId('111-7892341-9921045');
  };

  const resetForm = () => {
    setBuyer('');
    setGross('');
    setCountryCode('DE');
    setOrderId('');
  };

  return (
    <div className="max-w-2xl mx-auto bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-5 sm:p-7 shadow-xs text-slate-900 dark:text-white font-sans">
      {/* Top Banner */}
      <div className="no-print mb-6 pb-4 border-b border-slate-100 dark:border-slate-800">
        <div className="flex items-center justify-between gap-2">
          <span className="inline-flex items-center gap-1.5 bg-blue-50 dark:bg-blue-950/60 text-blue-700 dark:text-blue-400 text-xs font-bold px-3 py-1 rounded-full">
            <ShieldCheck className="w-3.5 h-3.5" />
            EU OSS Ready • 100% Free &amp; Client-Side
          </span>
          <div className="flex gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={loadSample}
              className="text-xs font-semibold rounded-xl cursor-pointer"
            >
              Load Sample
            </Button>
            <Button
              variant="ghost"
              size="sm"
              onClick={resetForm}
              className="text-xs font-medium rounded-xl cursor-pointer text-slate-500"
            >
              <RotateCcw className="w-3.5 h-3.5" />
            </Button>
          </div>
        </div>

        <h1 className="text-2xl sm:text-3xl font-black mt-3 tracking-tight">
          Amazon EU VAT Calculator
        </h1>
        <p className="text-slate-600 dark:text-slate-400 text-xs sm:text-sm mt-1.5 leading-relaxed">
          Calculate destination EU VAT rates, net turnover, and generate compliant invoices for Amazon sellers. Auto currency {country.symbol} {country.currency}.
        </p>
      </div>

      {/* Input Fields */}
      <div className="no-print space-y-4">
        <div>
          <label className="text-[11px] font-bold tracking-wider uppercase text-slate-700 dark:text-slate-300">
            BUYER / CUSTOMER NAME *
          </label>
          <input
            value={buyer}
            onChange={(e) => setBuyer(e.target.value)}
            className="w-full border border-slate-300 dark:border-slate-700 rounded-xl p-3 mt-1 bg-white dark:bg-slate-800 text-slate-900 dark:text-white outline-none focus:ring-2 focus:ring-blue-500 text-sm"
            placeholder="e.g. John Doe or Enterprise GmbH"
          />
        </div>

        <div>
          <label className="text-[11px] font-bold tracking-wider uppercase text-slate-700 dark:text-slate-300">
            GROSS ORDER TOTAL ({country.symbol} {country.currency}) *
          </label>
          <input
            value={gross}
            onChange={(e) => setGross(e.target.value)}
            type="number"
            step="0.01"
            className="w-full border border-slate-300 dark:border-slate-700 rounded-xl p-3 mt-1 bg-white dark:bg-slate-800 text-slate-900 dark:text-white outline-none focus:ring-2 focus:ring-blue-500 text-sm font-semibold"
            placeholder="e.g. 119.00"
          />
        </div>

        <div>
          <label className="text-[11px] font-bold tracking-wider uppercase text-slate-700 dark:text-slate-300">
            DESTINATION COUNTRY / TAX JURISDICTION
          </label>
          <select
            value={countryCode}
            onChange={(e) => setCountryCode(e.target.value)}
            className="w-full border border-slate-300 dark:border-slate-700 rounded-xl p-3 mt-1 bg-white dark:bg-slate-800 text-slate-900 dark:text-white outline-none focus:ring-2 focus:ring-blue-500 text-sm font-medium"
          >
            {COUNTRIES.map((c) => (
              <option key={c.code} value={c.code}>
                {c.label} - {c.currency} (Amazon.{c.marketplace})
              </option>
            ))}
          </select>
        </div>

        <div>
          <label className="text-[11px] font-bold tracking-wider uppercase text-slate-700 dark:text-slate-300">
            INVOICE / ORDER ID (OPTIONAL)
          </label>
          <input
            value={orderId}
            onChange={(e) => setOrderId(e.target.value)}
            className="w-full border border-slate-300 dark:border-slate-700 rounded-xl p-3 mt-1 bg-white dark:bg-slate-800 text-slate-900 dark:text-white outline-none focus:ring-2 focus:ring-blue-500 text-sm font-mono"
            placeholder="e.g. 111-1234567-1234567"
          />
        </div>
      </div>

      {/* Live Calculation Breakdown */}
      <div className="bg-[#F0F6FF] dark:bg-blue-950/40 border border-blue-100 dark:border-blue-900/60 rounded-2xl p-4 sm:p-5 mt-6">
        <div className="flex flex-wrap justify-between items-center gap-2">
          <span className="text-xs font-bold uppercase tracking-wider text-blue-950 dark:text-blue-200">
            LIVE CALCULATION BREAKDOWN
          </span>
          <span className="bg-white dark:bg-slate-800 border border-blue-200 dark:border-blue-800 text-xs px-3 py-1 rounded-full font-bold text-slate-800 dark:text-slate-200 shadow-xs">
            {country.name} • {country.rate}% {isExport ? 'Export' : 'VAT'}
          </span>
        </div>

        <div className="grid grid-cols-3 gap-3 mt-4">
          <div className="bg-white dark:bg-slate-800 rounded-xl p-3 text-center shadow-xs border border-blue-50 dark:border-slate-700">
            <div className="text-[11px] text-slate-500 dark:text-slate-400 font-medium">Net Turnover</div>
            <div className="font-bold text-sm sm:text-base text-slate-900 dark:text-white mt-0.5">
              {country.symbol} {net.toFixed(2)}
            </div>
          </div>
          <div className="bg-white dark:bg-slate-800 rounded-xl p-3 text-center shadow-xs border border-blue-50 dark:border-slate-700">
            <div className="text-[11px] text-slate-500 dark:text-slate-400 font-medium">VAT ({country.rate}%)</div>
            <div className="font-bold text-sm sm:text-base text-blue-600 dark:text-blue-400 mt-0.5">
              {country.symbol} {vatAmount.toFixed(2)}
            </div>
          </div>
          <div className="bg-white dark:bg-slate-800 rounded-xl p-3 text-center shadow-xs border border-blue-50 dark:border-slate-700">
            <div className="text-[11px] text-slate-500 dark:text-slate-400 font-medium">Gross Total</div>
            <div className="font-bold text-sm sm:text-base text-emerald-600 dark:text-emerald-400 mt-0.5">
              {country.symbol} {grossVal.toFixed(2)}
            </div>
          </div>
        </div>

        <div className="text-[11px] mt-3 bg-white dark:bg-slate-800 p-2.5 rounded-lg text-slate-600 dark:text-slate-300 border border-blue-100 dark:border-slate-700 leading-relaxed">
          {isExport
            ? `Export - Article 146 - No VAT - ${country.currency} compliant`
            : `OSS ID ${seller.ossId} - ${country.rate}% - ${country.currency} compliant - EU Directive 2006/112/EC`}
        </div>
      </div>

      {/* Validation warning */}
      {!canDownload && (
        <div className="bg-amber-50 dark:bg-amber-950/40 border border-amber-200 dark:border-amber-800/80 p-3 rounded-xl mt-4 text-xs font-semibold text-amber-900 dark:text-amber-300 flex items-center gap-2">
          <AlertTriangle className="w-4 h-4 shrink-0 text-amber-600" />
          <span>
            ⚠️ Required to unlock download: Please Complete:{' '}
            {!buyer ? 'Buyer Name' : ''} {!buyer && !grossVal ? ', ' : ''}{' '}
            {!grossVal ? 'Gross Amount' : ''}
          </span>
        </div>
      )}

      {/* Action Buttons */}
      <div className="no-print space-y-2 mt-4">
        <button
          disabled={!canDownload}
          onClick={downloadPdf}
          className={`w-full p-3.5 rounded-xl font-bold transition flex items-center justify-center gap-2 cursor-pointer shadow-sm text-sm ${
            canDownload
              ? 'bg-black dark:bg-white text-white dark:text-black hover:bg-slate-800 dark:hover:bg-slate-200'
              : 'bg-slate-200 dark:bg-slate-800 text-slate-400 dark:text-slate-600 cursor-not-allowed'
          }`}
        >
          <Download className="w-4 h-4" />
          {canDownload
            ? `Download 100% PASS PDF (${country.currency} ${grossVal.toFixed(2)})`
            : 'Fill All Fields to Enable Download'}
        </button>

        <div className="grid grid-cols-2 gap-2">
          <Button
            variant="outline"
            disabled={!canDownload}
            onClick={downloadTxt}
            className="text-xs font-bold rounded-xl cursor-pointer h-10 border-slate-300 dark:border-slate-700"
          >
            <FileText className="w-3.5 h-3.5 mr-1" /> Download Text (.txt)
          </Button>
          <Button
            variant="outline"
            disabled={!canDownload}
            onClick={handlePrint}
            className="text-xs font-bold rounded-xl cursor-pointer h-10 border-slate-300 dark:border-slate-700"
          >
            <Printer className="w-3.5 h-3.5 mr-1" /> Print / Save as PDF
          </Button>
        </div>

        <p className="text-emerald-600 dark:text-emerald-400 text-xs font-semibold flex items-center gap-1.5 pt-1">
          <CheckCircle2 className="w-3.5 h-3.5 shrink-0" />
          <span>✅ 100% Verified: Auto Currency ({country.currency}) | Article 146 | EU OSS Scheme | HS 8517.12.00</span>
        </p>
      </div>

      {/* Print Document Render */}
      <div
        id="print-area"
        className="hidden print:block mt-8 whitespace-pre-wrap font-mono text-xs border border-black p-6 bg-white text-black"
      >
        {generateInvoiceText()}
      </div>
    </div>
  );
}

export default AmazonEuVatTool;
