'use client';

import React, { useState } from 'react';
import jsPDF from 'jspdf';
import { ProToolBase } from '@/components/ProToolBase';
import { TOOLS } from '@/lib/config';
import { ArrowRightLeft, Calculator, Sparkles } from 'lucide-react';

const UNIT_CONVERSIONS: Record<string, { name: string; units: Record<string, number> }> = {
  length: {
    name: 'Length & Distance',
    units: {
      meters: 1,
      kilometers: 1000,
      centimeters: 0.01,
      millimeters: 0.001,
      miles: 1609.344,
      yards: 0.9144,
      feet: 0.3048,
      inches: 0.0254,
    },
  },
  weight: {
    name: 'Weight & Mass',
    units: {
      kilograms: 1,
      grams: 0.001,
      milligrams: 0.000001,
      pounds: 0.45359237,
      ounces: 0.028349523,
      metricTons: 1000,
    },
  },
  digital: {
    name: 'Digital Data',
    units: {
      megabytes: 1,
      gigabytes: 1024,
      terabytes: 1048576,
      kilobytes: 0.0009765625,
      bytes: 0.00000095367431640625,
    },
  },
};

export function UnitConverterTool() {
  const tool = TOOLS.find((t) => t.slug === 'unit-converter') || {
    slug: 'unit-converter',
    name: 'Unit Converter',
    desc: 'Convert length, weight, temperature & more instantly.',
    tag: 'Convert',
    colorIndex: 8,
  };

  const calculateResult = (
    valueStr: string,
    categoryKey: string,
    fromUnit: string,
    toUnit: string
  ) => {
    const val = parseFloat(valueStr);
    if (isNaN(val)) return null;

    const cat = UNIT_CONVERSIONS[categoryKey] || UNIT_CONVERSIONS.length;
    const fromFactor = cat.units[fromUnit] || 1;
    const toFactor = cat.units[toUnit] || 1;

    // Convert to base, then to target
    const baseVal = val * fromFactor;
    const targetVal = baseVal / toFactor;

    return {
      inputValue: val,
      fromUnit,
      toUnit,
      result: targetVal,
      categoryName: cat.name,
    };
  };

  const generateConversionSheetPdf = (form: Record<string, any>) => {
    const categoryKey = form.category || 'length';
    const fromUnit = form.fromUnit || 'meters';
    const toUnit = form.toUnit || 'feet';
    const res = calculateResult(form.inputValue, categoryKey, fromUnit, toUnit);

    if (!res) {
      alert('Please enter a valid numeric value to convert.');
      return;
    }

    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'pt',
      format: 'a4',
    });

    // Header
    doc.setFillColor(37, 99, 235);
    doc.rect(0, 0, 595, 75, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(22);
    doc.text('SCIENTIFIC CONVERSION SHEET', 40, 46);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('AllToolsPK Precision Dimensional Analysis • 100% Client-Side', 40, 64);

    // Primary Conversion Highlight Box
    doc.setFillColor(241, 245, 249);
    doc.roundedRect(40, 110, 515, 90, 8, 8, 'F');

    doc.setTextColor(71, 85, 105);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(`CATEGORY: ${res.categoryName.toUpperCase()}`, 60, 135);

    doc.setTextColor(15, 23, 42);
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text(
      `${res.inputValue} ${res.fromUnit}  =  ${res.result.toLocaleString(undefined, {
        maximumFractionDigits: 6,
      })} ${res.toUnit}`,
      60,
      170
    );

    // Full Category Conversion Matrix Table
    doc.setTextColor(30, 41, 59);
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.text('Equivalent Values in All Available Units:', 40, 240);

    const cat = UNIT_CONVERSIONS[categoryKey] || UNIT_CONVERSIONS.length;
    const baseVal = res.inputValue * (cat.units[fromUnit] || 1);

    let rowY = 270;
    doc.setFillColor(248, 250, 252);
    doc.rect(40, rowY - 16, 515, 25, 'F');
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text('Target Unit', 50, rowY);
    doc.text('Converted Magnitude', 300, rowY);
    rowY += 25;

    doc.setFont('helvetica', 'normal');
    doc.setTextColor(51, 65, 85);

    Object.entries(cat.units).forEach(([unitName, factor]) => {
      const equiv = baseVal / factor;
      doc.text(unitName.charAt(0).toUpperCase() + unitName.slice(1), 50, rowY);
      doc.text(equiv.toLocaleString(undefined, { maximumFractionDigits: 6 }), 300, rowY);
      rowY += 22;
    });

    // Mathematical Note
    doc.setDrawColor(226, 232, 240);
    doc.line(40, rowY + 15, 555, rowY + 15);

    doc.setFontSize(9);
    doc.setTextColor(148, 163, 184);
    doc.text(
      'Formulas follow international BIPM SI standards and US Customary definitions.',
      40,
      rowY + 35
    );
    doc.text(
      `Generated by alltoolspk.com on ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}`,
      40,
      rowY + 50
    );

    doc.save(`Conversion_${res.inputValue}_${res.fromUnit}_to_${res.toUnit}.pdf`);
  };

  return (
    <ProToolBase
      tool={tool}
      required={['inputValue', 'category', 'fromUnit', 'toUnit']}
      initialState={{
        inputValue: '',
        category: 'length',
        fromUnit: 'meters',
        toUnit: 'feet',
      }}
      render={(form, setForm) => {
        const categoryKey = form.category || 'length';
        const cat = UNIT_CONVERSIONS[categoryKey] || UNIT_CONVERSIONS.length;
        const fromUnit = form.fromUnit || Object.keys(cat.units)[0];
        const toUnit = form.toUnit || Object.keys(cat.units)[1];

        const res = form.inputValue ? calculateResult(form.inputValue, categoryKey, fromUnit, toUnit) : null;

        const handleCategoryChange = (newCat: string) => {
          const newUnits = Object.keys(UNIT_CONVERSIONS[newCat].units);
          setForm({
            ...form,
            category: newCat,
            fromUnit: newUnits[0],
            toUnit: newUnits[1] || newUnits[0],
          });
        };

        return (
          <div className="space-y-6">
            <div>
              <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 uppercase tracking-wider mb-1.5">
                Conversion Category
              </label>
              <div className="grid grid-cols-3 gap-2">
                {Object.entries(UNIT_CONVERSIONS).map(([key, data]) => (
                  <button
                    key={key}
                    type="button"
                    onClick={() => handleCategoryChange(key)}
                    className={`py-2.5 px-3 rounded-xl text-xs font-bold transition-all cursor-pointer ${
                      categoryKey === key
                        ? 'bg-blue-600 text-white shadow-sm'
                        : 'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300 hover:bg-slate-200 dark:hover:bg-slate-700'
                    }`}
                  >
                    {data.name}
                  </button>
                ))}
              </div>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 items-end">
              <div>
                <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 uppercase tracking-wider mb-1.5">
                  Input Value *
                </label>
                <input
                  type="number"
                  step="any"
                  placeholder="e.g. 100"
                  value={form.inputValue || ''}
                  onChange={(e) => setForm({ ...form, inputValue: e.target.value })}
                  className="w-full px-4 py-3 rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-sm focus:ring-2 focus:ring-blue-600 outline-none"
                />
              </div>

              <div>
                <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 uppercase tracking-wider mb-1.5">
                  From Unit
                </label>
                <select
                  value={fromUnit}
                  onChange={(e) => setForm({ ...form, fromUnit: e.target.value })}
                  className="w-full px-4 py-3 rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-sm focus:ring-2 focus:ring-blue-600 outline-none cursor-pointer capitalize"
                >
                  {Object.keys(cat.units).map((u) => (
                    <option key={u} value={u}>
                      {u}
                    </option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 uppercase tracking-wider mb-1.5">
                  To Unit
                </label>
                <select
                  value={toUnit}
                  onChange={(e) => setForm({ ...form, toUnit: e.target.value })}
                  className="w-full px-4 py-3 rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-sm focus:ring-2 focus:ring-blue-600 outline-none cursor-pointer capitalize"
                >
                  {Object.keys(cat.units).map((u) => (
                    <option key={u} value={u}>
                      {u}
                    </option>
                  ))}
                </select>
              </div>
            </div>

            {/* Instant Result Box */}
            {res && (
              <div className="p-6 rounded-2xl bg-blue-50/60 dark:bg-blue-950/40 border border-blue-100 dark:border-blue-900/60 text-center space-y-1">
                <span className="text-xs font-bold uppercase tracking-wider text-blue-600 dark:text-blue-400">
                  Calculated Result
                </span>
                <p className="text-2xl sm:text-3xl font-black text-slate-900 dark:text-white">
                  {res.result.toLocaleString(undefined, { maximumFractionDigits: 6 })}{' '}
                  <span className="text-sm font-semibold text-slate-500 capitalize">{res.toUnit}</span>
                </p>
                <p className="text-xs text-slate-500">
                  1 {res.fromUnit} ={' '}
                  {((cat.units[fromUnit] || 1) / (cat.units[toUnit] || 1)).toLocaleString(undefined, {
                    maximumFractionDigits: 6,
                  })}{' '}
                  {res.toUnit}
                </p>
              </div>
            )}
          </div>
        );
      }}
      generateFile={generateConversionSheetPdf}
    />
  );
}

export default UnitConverterTool;
