'use client';

import React, { useState } from 'react';
import { DollarSign, Printer, Download, Sparkles, CheckCircle2, RefreshCw } from 'lucide-react';
import { Button } from '@/components/ui/button';

export function USAPaycheckCalculator2026() {
  const [salary, setSalary] = useState(75000);
  const [status, setStatus] = useState<'single' | 'married' | 'hoh' | 'separate'>('single');
  const [stateTaxRate, setStateTaxRate] = useState(5);
  const [k401, setK401] = useState(6);
  const [payFreq, setPayFreq] = useState<'annual' | 'monthly' | 'biweekly' | 'weekly'>('biweekly');

  // 2026 IRS Data - Verified
  const stdDeduction: Record<string, number> = {
    single: 16100,
    married: 32200,
    hoh: 24150,
    separate: 16100,
  };

  const brackets: Record<string, [number, number][]> = {
    single: [
      [12400, 0.10],
      [50400, 0.12],
      [105700, 0.22],
      [201775, 0.24],
      [256225, 0.32],
      [640600, 0.35],
      [Infinity, 0.37],
    ],
    married: [
      [24800, 0.10],
      [100800, 0.12],
      [211400, 0.22],
      [403550, 0.24],
      [512450, 0.32],
      [768700, 0.35],
      [Infinity, 0.37],
    ],
    hoh: [
      [17700, 0.10],
      [67450, 0.12],
      [105700, 0.22],
      [201775, 0.24],
      [256200, 0.32],
      [640600, 0.35],
      [Infinity, 0.37],
    ],
    separate: [
      [12400, 0.10],
      [50400, 0.12],
      [105700, 0.22],
      [201775, 0.24],
      [256225, 0.32],
      [640600, 0.35],
      [Infinity, 0.37],
    ],
  };

  const calculate = () => {
    const safeSalary = Math.max(0, salary || 0);
    const ded401 = safeSalary * (Math.max(0, k401) / 100);
    const deduction = stdDeduction[status] || stdDeduction.single;
    const taxableIncome = Math.max(0, safeSalary - ded401 - deduction);
    
    let fedTax = 0;
    let prev = 0;
    const activeBrackets = brackets[status] || brackets.single;
    for (const [limit, rate] of activeBrackets) {
      if (taxableIncome > prev) {
        const taxableAtBracket = Math.min(taxableIncome, limit) - prev;
        fedTax += taxableAtBracket * rate;
        prev = limit;
      }
    }

    const ssTax = Math.min(safeSalary, 184500) * 0.062;
    const medTax = safeSalary * 0.0145 + (safeSalary > 200000 ? (safeSalary - 200000) * 0.009 : 0);
    const stateTax = Math.max(0, safeSalary - ded401) * (Math.max(0, stateTaxRate) / 100);
    const takeHome = Math.max(0, safeSalary - ded401 - fedTax - ssTax - medTax - stateTax);

    return { ded401, fedTax, ssTax, medTax, stateTax, takeHome, taxableIncome, deduction };
  };

  const r = calculate();
  const freqDiv = payFreq === 'weekly' ? 52 : payFreq === 'biweekly' ? 26 : payFreq === 'monthly' ? 12 : 1;

  const handlePrint = () => {
    try {
      window.print();
    } catch {
      // ignore
    }
  };

  const handleDownloadSummary = () => {
    const summary = `USA PAYCHECK & TAKE-HOME TAX REPORT (2026 TAX YEAR)
Generated by AllToolsPK (https://alltoolspk.com)
Date: ${new Date().toLocaleDateString('en-US', { dateStyle: 'full' })}

INCOME & FILING DETAILS:
- Annual Gross Salary: $${salary.toLocaleString()}
- Filing Status: ${status.toUpperCase()}
- 401(k) Pre-Tax Contribution: ${k401}% ($${r.ded401.toFixed(2)})
- State Tax Rate: ${stateTaxRate}%
- Pay Frequency: ${payFreq.toUpperCase()}

2026 TAX CALCULATIONS & DEDUCTIONS:
- 2026 Standard Deduction: $${r.deduction.toLocaleString()}
- Taxable Federal Income: $${r.taxableIncome.toFixed(2)}
- Federal Income Tax (2026 Brackets): $${r.fedTax.toFixed(2)}
- Social Security Tax (6.2% cap $184,500): $${r.ssTax.toFixed(2)}
- Medicare Tax (1.45% + Addl Medicare): $${r.medTax.toFixed(2)}
- Total FICA Taxes: $${(r.ssTax + r.medTax).toFixed(2)}
- State Income Tax: $${r.stateTax.toFixed(2)}

NET TAKE-HOME PAY:
- Annual Take-Home Pay: $${r.takeHome.toFixed(2)}
- Take-Home per ${payFreq}: $${(r.takeHome / freqDiv).toFixed(2)}
- Effective Hourly (2,080 standard hours): $${(r.takeHome / 2080).toFixed(2)}/hr

* Note: Calculated based on IRS 2026 inflation-adjusted tax brackets and standard deductions. Consult IRS Form W-4 for personal withholding allowances.`;

    const blob = new Blob([summary], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Paycheck_Calculation_2026_${salary}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-4xl mx-auto p-4 sm:p-6 my-6 bg-white dark:bg-slate-900 rounded-3xl shadow-xl border border-slate-200 dark:border-slate-800 text-slate-900 dark:text-slate-100 transition-colors">
      {/* Modern Icon & Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-8 pb-6 border-b border-slate-100 dark:border-slate-800">
        <div className="flex items-center gap-3.5">
          <div
            className="w-14 h-14 rounded-2xl bg-gradient-to-br from-emerald-600 via-teal-600 to-blue-600 flex items-center justify-center text-white text-2xl shadow-md shrink-0"
            aria-label="USA Paycheck Calculator 2026 Icon"
            title="USA Paycheck Calculator 2026"
          >
            💵
          </div>
          <div>
            <div className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-[11px] font-bold bg-emerald-50 dark:bg-emerald-950/60 text-emerald-600 dark:text-emerald-400 border border-emerald-200/80 dark:border-emerald-800/60 mb-1">
              <Sparkles className="w-3 h-3" />
              <span>2026 IRS Data • 100% Client-Side</span>
            </div>
            <h1 className="text-2xl sm:text-3xl font-extrabold text-slate-900 dark:text-white tracking-tight">
              USA Paycheck Calculator 2026
            </h1>
            <p className="text-slate-500 dark:text-slate-400 text-xs sm:text-sm">
              Calculate exact take-home pay after Federal, State, 401(k), and FICA taxes.
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <Button
            variant="outline"
            size="sm"
            onClick={handleDownloadSummary}
            className="text-xs font-bold rounded-xl cursor-pointer border-slate-300 dark:border-slate-700"
          >
            <Download className="w-3.5 h-3.5 mr-1" /> Save Report
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={handlePrint}
            className="text-xs font-bold rounded-xl cursor-pointer border-slate-300 dark:border-slate-700"
          >
            <Printer className="w-3.5 h-3.5 mr-1" /> Print
          </Button>
        </div>
      </div>

      <div className="grid md:grid-cols-2 gap-8">
        {/* Form Inputs */}
        <div className="space-y-4">
          <div>
            <label className="block text-xs font-bold uppercase tracking-wider text-slate-600 dark:text-slate-300 mb-1.5">
              Annual Gross Salary ($)
            </label>
            <div className="relative">
              <span className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400 font-bold">$</span>
              <input
                type="number"
                min="0"
                step="1000"
                value={salary}
                onChange={(e) => setSalary(Number(e.target.value))}
                className="w-full pl-8 pr-4 py-3 bg-slate-50 dark:bg-slate-800/80 border border-slate-200 dark:border-slate-700 rounded-xl font-semibold text-slate-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-emerald-500"
                placeholder="75000"
              />
            </div>
          </div>

          <div>
            <label className="block text-xs font-bold uppercase tracking-wider text-slate-600 dark:text-slate-300 mb-1.5">
              Filing Status
            </label>
            <select
              value={status}
              onChange={(e) => setStatus(e.target.value as any)}
              className="w-full p-3 bg-slate-50 dark:bg-slate-800/80 border border-slate-200 dark:border-slate-700 rounded-xl font-semibold text-slate-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-emerald-500 cursor-pointer"
            >
              <option value="single">Single (Std Ded: $16,100)</option>
              <option value="married">Married Filing Jointly (Std Ded: $32,200)</option>
              <option value="hoh">Head of Household (Std Ded: $24,150)</option>
              <option value="separate">Married Filing Separately (Std Ded: $16,100)</option>
            </select>
          </div>

          <div>
            <div className="flex justify-between items-center mb-1.5">
              <label className="block text-xs font-bold uppercase tracking-wider text-slate-600 dark:text-slate-300">
                State Tax Rate (%)
              </label>
              <span className="text-[11px] text-slate-400 font-medium">TX/FL=0, WA=0, CA~9.3, NY~6</span>
            </div>
            <div className="relative">
              <input
                type="number"
                min="0"
                max="15"
                step="0.1"
                value={stateTaxRate}
                onChange={(e) => setStateTaxRate(Number(e.target.value))}
                className="w-full p-3 bg-slate-50 dark:bg-slate-800/80 border border-slate-200 dark:border-slate-700 rounded-xl font-semibold text-slate-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-emerald-500"
              />
              <span className="absolute right-3.5 top-1/2 -translate-y-1/2 text-slate-400 font-bold">%</span>
            </div>
          </div>

          <div>
            <div className="flex justify-between items-center mb-1.5">
              <label className="block text-xs font-bold uppercase tracking-wider text-slate-600 dark:text-slate-300">
                401(k) Pre-Tax Contribution (%)
              </label>
              <span className="text-[11px] text-emerald-600 dark:text-emerald-400 font-semibold">
                Saves ${(r.ded401).toFixed(0)} pre-tax
              </span>
            </div>
            <div className="relative">
              <input
                type="number"
                min="0"
                max="50"
                step="0.5"
                value={k401}
                onChange={(e) => setK401(Number(e.target.value))}
                className="w-full p-3 bg-slate-50 dark:bg-slate-800/80 border border-slate-200 dark:border-slate-700 rounded-xl font-semibold text-slate-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-emerald-500"
              />
              <span className="absolute right-3.5 top-1/2 -translate-y-1/2 text-slate-400 font-bold">%</span>
            </div>
          </div>

          <div>
            <label className="block text-xs font-bold uppercase tracking-wider text-slate-600 dark:text-slate-300 mb-1.5">
              Pay Frequency
            </label>
            <select
              value={payFreq}
              onChange={(e) => setPayFreq(e.target.value as any)}
              className="w-full p-3 bg-slate-50 dark:bg-slate-800/80 border border-slate-200 dark:border-slate-700 rounded-xl font-semibold text-slate-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-emerald-500 cursor-pointer"
            >
              <option value="annual">Annual (1 pay period)</option>
              <option value="monthly">Monthly (12 pay periods)</option>
              <option value="biweekly">Bi-Weekly (26 pay periods - Standard US)</option>
              <option value="weekly">Weekly (52 pay periods)</option>
            </select>
          </div>
        </div>

        {/* Results Breakdown */}
        <div className="bg-slate-50 dark:bg-slate-800/60 p-6 rounded-2xl border border-slate-200/80 dark:border-slate-700/80 flex flex-col justify-between">
          <div>
            <div className="flex items-center justify-between pb-3 border-b border-slate-200 dark:border-slate-700 mb-4">
              <h3 className="font-extrabold text-slate-900 dark:text-white text-base">
                Take-Home Breakdown (2026)
              </h3>
              <span className="text-xs font-bold px-2 py-0.5 rounded-full bg-emerald-100 dark:bg-emerald-950 text-emerald-700 dark:text-emerald-300">
                Gross: ${salary.toLocaleString()}
              </span>
            </div>

            <div className="space-y-2.5 text-sm">
              <div className="flex justify-between items-center text-slate-600 dark:text-slate-300">
                <span>401(k) Pre-Tax Savings:</span>
                <b className="font-bold text-slate-900 dark:text-white">
                  ${r.ded401.toFixed(0)}
                </b>
              </div>

              <div className="flex justify-between items-center text-slate-600 dark:text-slate-300">
                <span>Federal Tax (2026 IRS Brackets):</span>
                <b className="font-bold text-rose-600 dark:text-rose-400">
                  -${r.fedTax.toFixed(0)}
                </b>
              </div>

              <div className="flex justify-between items-center text-slate-600 dark:text-slate-300">
                <span>State Income Tax ({stateTaxRate}%):</span>
                <b className="font-bold text-rose-600 dark:text-rose-400">
                  -${r.stateTax.toFixed(0)}
                </b>
              </div>

              <div className="flex justify-between items-center text-slate-600 dark:text-slate-300">
                <span>FICA (Social Security 6.2% + Medicare):</span>
                <b className="font-bold text-rose-600 dark:text-rose-400">
                  -${(r.ssTax + r.medTax).toFixed(0)}
                </b>
              </div>

              <div className="pt-3 border-t border-slate-200 dark:border-slate-700 space-y-2">
                <div className="flex justify-between items-center">
                  <span className="font-bold text-slate-800 dark:text-slate-200 text-base">
                    Annual Net Take-Home:
                  </span>
                  <b className="text-xl font-black text-emerald-600 dark:text-emerald-400">
                    ${r.takeHome.toFixed(0)}
                  </b>
                </div>

                <div className="flex justify-between items-center bg-white dark:bg-slate-900 p-3 rounded-xl border border-slate-200/80 dark:border-slate-700/80">
                  <span className="font-extrabold text-slate-900 dark:text-white capitalize">
                    Per {payFreq} Paycheck:
                  </span>
                  <b className="text-xl font-black text-emerald-600 dark:text-emerald-400">
                    ${(r.takeHome / freqDiv).toFixed(2)}
                  </b>
                </div>

                <div className="flex justify-between items-center text-xs text-slate-500 dark:text-slate-400 pt-1">
                  <span>Effective Hourly (2,080 standard hours/year):</span>
                  <b className="font-bold text-slate-700 dark:text-slate-300">
                    ${(r.takeHome / 2080).toFixed(2)}/hr
                  </b>
                </div>
              </div>
            </div>
          </div>

          <div className="mt-6 pt-4 border-t border-slate-200 dark:border-slate-700 text-[11px] text-slate-400 space-y-1">
            <p className="flex items-center gap-1 text-emerald-600 dark:text-emerald-400 font-semibold">
              <CheckCircle2 className="w-3.5 h-3.5 shrink-0" />
              <span>Verified 2026 IRS Standard Deductions: Single $16,100 | MFJ $32,200 | HoH $24,150</span>
            </p>
            <p>SS Wage Base Cap: $184,500. Addl Medicare Tax applied over $200k. 100% private client calculation.</p>
          </div>
        </div>
      </div>

      {/* --- ADSENSE SEO CONTENT - PASTE THIS AT BOTTOM --- */}
      <div className="mt-12 p-6 bg-white dark:bg-slate-800/90 rounded-2xl shadow-sm border border-slate-200 dark:border-slate-700 text-left">
        <h2 className="text-2xl font-bold mb-4 text-slate-900 dark:text-white">How to Use USA Paycheck Calculator 2026?</h2>
        <ol className="list-decimal ml-5 space-y-2 text-slate-700 dark:text-slate-300">
          <li>Enter your Annual Gross Salary (e.g. $40,000).</li>
          <li>Select Filing Status - Single, Married Jointly, Head of Household. Standard deduction 2026 will auto-apply.</li>
          <li>Enter your State Tax Rate - 0% for TX/FL, 5-9.3% for other states.</li>
          <li>Enter 401(k) contribution % to see pre-tax savings.</li>
          <li>Your Take-Home, Federal Tax, FICA, and Biweekly Paycheck will calculate 100% client-side.</li>
        </ol>

        <h2 className="text-2xl font-bold mt-8 mb-4 text-slate-900 dark:text-white">About USA Paycheck & Take-Home Pay 2026</h2>
        <p className="text-slate-700 dark:text-slate-300 leading-relaxed">
          Our USA Paycheck Calculator 2026 uses verified 2026 IRS tax brackets, Standard Deduction (Single $16,100, MFJ $32,200, HoH $24,150), 
          Social Security wage cap $184,500, and Medicare 1.45% to give you exact annual and biweekly take-home pay. All calculations are 100% private 
          and done in your browser - no data is sent to our server. This tool helps US employees in all 50 states to plan salary, 401k, and state taxes.
        </p>

        <h3 className="text-xl font-bold mt-6 mb-3 text-slate-900 dark:text-white">Formula Used:</h3>
        <p className="bg-slate-100 dark:bg-slate-900/80 p-3 rounded-lg font-mono text-sm text-slate-800 dark:text-slate-200 border border-slate-200 dark:border-slate-800">
          Taxable Income = (Gross - 401k) - Standard Deduction<br/>
          Net Pay = Gross - 401k - Federal Tax - State Tax - FICA
        </p>

        <h2 className="text-2xl font-bold mt-8 mb-4 text-slate-900 dark:text-white">FAQs</h2>
        <p className="text-slate-700 dark:text-slate-300"><b className="text-slate-900 dark:text-white">Q: Is this 2026 IRS data accurate?</b><br/>A: Yes, we use inflation-adjusted 2026 IRS brackets and SS cap $184,500.</p>
        <p className="mt-3 text-slate-700 dark:text-slate-300"><b className="text-slate-900 dark:text-white">Q: Does it support 401k?</b><br/>A: Yes, enter any % and it will show pre-tax savings and reduce taxable income.</p>
      </div>
    </div>
  );
}

export default USAPaycheckCalculator2026;
